### ISSUE TITLE
Support the Fixed-Limit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ericmas001/BluffinMuffin.Beta#15]
```
Support the Fixed-Limit 
http://www.pokerlistings.com/texas-holdem-betting-rules
```

Original issue reported on code.google.com by `ericmas001@gmail.com` on 13 Apr 2014 at 8:39

**Comment by Ericmas001** [comment]
Duplicated in Ericmas001/BluffinMuffin.Server
