### ISSUE TITLE
Add a "Omaha Holdem" variant 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ericmas001/BluffinMuffin.Beta#19]
```
Add a "Omaha Holdem" variant 

http://en.wikipedia.org/wiki/Omaha_hold_'em
```

Original issue reported on code.google.com by `ericmas001@gmail.com` on 13 Apr 2014 at 8:41

**Comment by Ericmas001** [comment]
Duplicated in Ericmas001/BluffinMuffin.Server
